# Descriptive stats

In [1]:
from pandas.core.common import random_state
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\abc\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abc\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abc\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abc\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abc\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\abc\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Age" : [22, 35, 29, 48, None],
    "Fare" : [7.25, 71.28, 7.93, 53.10, 8.05]
})
print(df["Age"].mean())
print(df.median())
print(df[["Age", "Fare"]].describe())

33.5
Age     32.00
Fare     8.05
dtype: float64
             Age       Fare
count   4.000000   5.000000
mean   33.500000  29.522000
std    11.030261  30.508015
min    22.000000   7.250000
25%    27.250000   7.930000
50%    32.000000   8.050000
75%    38.250000  53.100000
max    48.000000  71.280000

# Grouped Stats

In [3]:
titanic = pd.DataFrame({
    "sex" : ["female", "male", "male", "female"],
    "age" : [27.9, 30.7, 22.0, 35.0],
    "fare" : [44.5, 25.5, 7.9, 106.1]
})

print(titanic.groupby("sex")["age"].mean())
print(titanic.groupby(["sex"]).mean(numeric_only=True))

sex
female    31.45
male      26.35
Name: age, dtype: float64
          age  fare
sex
female  31.45  75.3
male    26.35  16.7

# Frequency counts

In [4]:
s = pd.Series(["A", "B", "A", "C", "B", "B", None])
print(s.value_counts()) # Count excluding NaNs
print(s.value_counts(dropna=False)) # Count including NaNs

B    3
A    2
C    1
Name: count, dtype: int64
B       3
A       2
C       1
None    1
Name: count, dtype: int64

# Custom Aggregations

In [5]:
df = pd.DataFrame({
    "Age": [22, 35, 29, 40],
    "Fare": [7.25, 71.28, 7.93, 53.10]
})

df_agg = df.agg({
    "Age" : ["mean", "min", "max", "skew", "count"],
    "Fare" : ["mean", "min", "max", "skew", "count"]
})

df_agg

             Age       Fare
mean   31.500000  34.890000
min    22.000000   7.250000
max    40.000000  71.280000
skew   -0.307274   0.265248
count   4.000000   4.000000

# Computing changes over time with .pct_change()

In [6]:
import numpy as np
s = pd.Series([1,2,3,4,5,4])

print(s.pct_change())

0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.250000
5   -0.200000
dtype: float64

In [7]:
df = pd.DataFrame(np.random.randn(5,2))

print(df.pct_change()) # Row-wise changes
print(df.pct_change(axis=1)) # Column-wise changes

           0         1
0        NaN       NaN
1  -1.101708 -5.347612
2 -60.850684 -5.120862
3  -0.654969 -1.170239
4  -0.454018 -9.795787
    0         1
0 NaN -0.830506
1 NaN  6.245189
2 NaN -0.501151
3 NaN -1.246133
4 NaN  2.965208

# Correlation and covariance

In [8]:
frame = pd.DataFrame(np.random.randn(10, 3), columns= ["a", "b", "c"])
print(frame)
cov_a_b = frame["a"].cov(frame["b"])
print(f"\nCovariance between column 'a' and 'b' is {cov_a_b}")
print(frame.cov())

          a         b         c
0  0.116483  1.098727 -0.592458
1 -0.460214 -0.548392  0.017461
2  1.699792  1.806182  0.553768
3  0.672743 -1.497586  0.446949
4  0.150016 -0.245534 -0.075832
5 -0.894582 -1.098940 -0.889968
6  1.062468 -0.405450 -0.495277
7  1.432370  0.634495  0.776754
8 -0.488701  0.473305  1.014999
9  1.074938  0.207235 -0.787605

Covariance between column 'a' and 'b' is 0.4081854160661341
          a         b         c
a  0.784363  0.408185  0.134117
b  0.408185  1.010767  0.186571
c  0.134117  0.186571  0.461625

# Ranking

In [14]:
s = pd.Series([10, 30, 20, 30])
print(s.rank())                # Average rank on ties
print(s.rank(method="min"))    # Lowest rank on ties
print(s.rank(ascending=False)) # Reverse ranking

0    1.0
1    3.5
2    2.0
3    3.5
dtype: float64
0    1.0
1    3.0
2    2.0
3    3.0
dtype: float64
0    4.0
1    1.5
2    3.0
3    1.5
dtype: float64

# Rolling windows

In [22]:
s = pd.Series(range(5))
print(s.rolling(window=2).sum()) # fixed-size rolling sum

s2 = pd.Series(range(5), index= pd.date_range('2025-01-01', periods=5, freq='D'))
s2.rolling(window="2D").sum()

0    NaN
1    1.0
2    3.0
3    5.0
4    7.0
dtype: float64

2025-01-01    0.0
2025-01-02    1.0
2025-01-03    3.0
2025-01-04    5.0
2025-01-05    7.0
Freq: D, dtype: float64

# Expanding windows

In [24]:
df = pd.DataFrame({"x": [0,1,2,3,4]})
print(df.expanding(min_periods=2).mean()) # cumlative mean

     x
0  NaN
1  0.5
2  1.0
3  1.5
4  2.0

# Exponentially weighted

In [27]:
df = pd.DataFrame({"x" : [0, 1, 2, np.nan, 4]})
times = pd.date_range("2025/01/01", periods=5, freq="D")
df.ewm(halflife= "4 days", times=times).mean()

          x
0  0.000000
1  0.543214
2  1.114950
3  1.114950
4  2.144696